services:
  mysql:
    image: mysql:8.0
    container_name: bench_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: benchmark_test
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bench_sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Benchmark@123
    ports:
      - "1433:1433"

  postgresql:
    image: postgres:18-alpine
    container_name: bench_postgresql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: benchmark_test
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:8.0
    container_name: bench_mongodb
    ports:
      - "27017:27017"